#!/bin/bash
URL=https://raw.githubusercontent.com/pkolmykov/jetty-openshift-java8/master/

curl -s ${URL}java_setup.sh | bash -s "http://download.oracle.com/otn-pub/java/jdk/8u20-b26/jdk-8u20-linux-x64.tar.gz"
curl -s ${URL}jetty_setup.sh | bash -s "http://eclipse.org/downloads/download.php?file=/jetty/stable-9/dist/jetty-distribution-9.2.3.v20140905.tar.gz&r=1"
curl -s ${URL}build.sh | bash
curl -s ${URL}start.sh | bash
